import json
import re
from odoo import models, fields, _
from odoo.exceptions import UserError


class AiBlogProposal(models.Model):
    _name = 'ai.blog.proposal'
    _description = 'AI Blog Proposal'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _rec_name = 'title'
    _order = 'relevance_score desc, create_date desc'

    title = fields.Char(string='Suggested Title', required=True, tracking=True)
    summary = fields.Text(string='Subject Summary')
    context_identified = fields.Text(string='Identified Context')
    editorial_angle = fields.Text(string='Editorial Angle')
    sources = fields.Text(string='Potential Sources')
    relevance_score = fields.Float(string='Relevance Score', digits=(3, 1))
    relevance_justification = fields.Text(string='Selection Justification')

    domain_id = fields.Many2one('ai.blog.domain', string='Domain', required=True)
    extra_instructions = fields.Text(string='Additional Instructions for Writer')

    blog_id = fields.Many2one('blog.blog', string='Target Blog')
    blog_post_id = fields.Many2one('blog.post', string='Generated Blog Post', readonly=True)

    state = fields.Selection([
        ('pending', 'Pending Validation'),
        ('validated', 'Validated'),
        ('rejected', 'Rejected'),
        ('done', 'Article Generated'),
    ], default='pending', string='Status', tracking=True, required=True)

    def action_validate(self):
        for rec in self:
            rec.state = 'validated'
            rec.message_post(body=_('Proposal validated.'))

    def action_reject(self):
        for rec in self:
            rec.state = 'rejected'
            rec.message_post(body=_('Proposal rejected.'))

    def action_view_blog_post(self):
        self.ensure_one()
        return {
            'type': 'ir.actions.act_window',
            'name': _('Blog Post'),
            'res_model': 'blog.post',
            'res_id': self.blog_post_id.id,
            'view_mode': 'form',
            'target': 'current',
        }

    def action_generate_article(self):
        self.ensure_one()

        provider = self.env['ai.blog.provider'].search(
            [('is_default', '=', True), ('active', '=', True)], limit=1
        )
        if not provider:
            provider = self.env['ai.blog.provider'].search([('active', '=', True)], limit=1)
        if not provider:
            raise UserError(_('No active AI provider configured.'))

        keyword_str = ', '.join(self.domain_id.keyword_ids.mapped('name'))
        language = (self.domain_id.language_id.code or 'en').split('_')[0]

        prompt = self._build_writer_prompt(keyword_str, language)

        try:
            raw_response = provider.call(prompt, max_tokens=16384)
        except Exception as e:
            raise UserError(_('AI provider call failed: %s') % str(e))

        article_data = self._parse_writer_response(raw_response)

        blog = self.blog_id or self.env['blog.blog'].search([], limit=1)
        if not blog:
            raise UserError(_('No blog found. Please create a blog in Website first.'))

        tag_ids = []
        for tag_name in (article_data.get('tags') or []):
            tag_name = (tag_name or '').strip()
            if not tag_name:
                continue
            tag = self.env['blog.tag'].search([('name', '=ilike', tag_name)], limit=1)
            if not tag:
                tag = self.env['blog.tag'].create({'name': tag_name})
            tag_ids.append(tag.id)

        blog_post = self.env['blog.post'].create({
            'name': article_data.get('title') or self.title,
            'blog_id': blog.id,
            'content': article_data.get('content', ''),
            'website_meta_description': (article_data.get('meta_description') or '')[:160],
            'tag_ids': [(6, 0, tag_ids)],
            'is_published': False,
        })

        self.write({
            'blog_post_id': blog_post.id,
            'state': 'done',
        })
        self.message_post(body=_('Article generated by AI provider "%s".') % provider.name)

        return {
            'type': 'ir.actions.act_window',
            'name': _('Blog Post'),
            'res_model': 'blog.post',
            'res_id': blog_post.id,
            'view_mode': 'form',
            'target': 'current',
        }

    def _build_writer_prompt(self, keyword_str, language):
        lines = [
            'You are an expert SEO blog writer.',
            f'Write a complete, high-quality blog post in language code "{language}" for the proposal below.\n',
            f'Proposed title: {self.title}',
            f'Keywords to include naturally: {keyword_str}',
        ]
        if self.summary:
            lines.append(f'Subject summary: {self.summary}')
        if self.context_identified:
            lines.append(f'Context: {self.context_identified}')
        if self.editorial_angle:
            lines.append(f'Editorial angle: {self.editorial_angle}')
        if self.sources:
            lines.append(f'Sources to reference: {self.sources}')
        if self.extra_instructions:
            lines.append(f'Additional instructions: {self.extra_instructions}')

        lines += [
            '\nIMPORTANT: Return ONLY a raw JSON object. No markdown, no code fences, no explanation.',
            'The JSON must have exactly these keys:',
            '{',
            '  "title": "Final SEO-optimized blog post title",',
            '  "meta_description": "SEO meta description, strictly 150-160 characters",',
            '  "content": "<p>Full HTML content...</p>",',
            '  "tags": ["tag1", "tag2", "tag3"]',
            '}',
            '\nContent requirements:',
            '- Minimum 600 words',
            '- Well structured: introduction, H2/H3 sections, conclusion',
            '- Use only HTML tags: p, h2, h3, ul, li, strong, em',
            '- Keywords included naturally throughout',
            '- 3 to 6 relevant tags',
            '- meta_description between 150 and 160 characters exactly',
            '- Escape all double quotes inside HTML attribute values',
        ]
        return '\n'.join(lines)

    def _parse_writer_response(self, raw_response):
        text = raw_response.strip()

        fenced = re.search(r'```(?:json)?\s*([\s\S]*?)\s*```', text)
        if fenced:
            text = fenced.group(1).strip()

        if not text.startswith('{'):
            obj_match = re.search(r'\{[\s\S]*\}', text)
            if obj_match:
                text = obj_match.group()

        try:
            return json.loads(text)
        except json.JSONDecodeError:
            raise UserError(
                _('Could not parse the AI response as JSON.\nRaw response (first 500 chars):\n%s')
                % raw_response[:500]
            )
